language: node_js

node_js:
   - "5"
   - "4"

script:
   - istanbul cover --print none --report lcovonly -x 'test/*' test/compiler.js

after_success:
   - cat ./coverage/lcov.info |coveralls && rm -fr ./coverage
